config/routes.rb
Rails.application.routes.draw do
  scope format: false do
    # MUST COME FIRST: Redirect apex requests to www
    match '(*any)', via: :all, constraints: { subdomain: '' }, to: redirect { |_, req| req.url.sub '//', '//www.' }

    # Retail
    root "totem#index"
    get "checkout" => "static#checkout"
    get "payment" => "static#payment"
    get "order-complete/:id" => "retail_orders#order_complete", as: "order_complete"
    resources :orders, only: [:create, :show], controller: "retail_orders"

    # Static
    get "about" => "static#about"
    get "events" => "static#events"
    get "locations" => "static#locations"
    get "press" => "static#press"
    get "catalog" => "static#catalog"
    get "robots.txt" => "static#robots"

    # Static — Admin
    get "stink" => "static#stink"
    post "stink" => "static#stink_in"
    delete "stink" => "static#stink_out"

    # Tips
    get "tips/double-wrap-belt" => redirect("tips/double-wrap-belt.pdf")

    # Wholesale — both
    get "wholesale/policies" => "wholesales#policies", as: :wholesale_policies
    get "merchant/logout" => "merchant#logout", as: "logout_merchant"
    get "order/:id/invoice" => "wholesales#invoice", as: :wholesale_order_invoice
    post "order/:id/pay" => "wholesales#pay", as: :wholesale_pay_invoice

    # Wholesale — public
    scope constraints: lambda { |request| request.session[:merchant_id].nil? || Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#login"
      post "merchant" => "merchant#login_post"

      get "merchant/check-password" => "merchant#check_password"
      post "merchant/check-password" => "merchant#check_password_post"

      get "merchant/create-password" => "merchant#create_password"
      post "merchant/create-password" => "merchant#create_password_post"

      get "merchant/details" => "merchant#details"
      post "merchant/details" => "merchant#details_post"

      get "merchant/send-password-reset" => "merchant#send_password_reset"
      get "merchant/password-reset-sent" => "merchant#password_reset_sent"

      get "merchant/reset-password/:token" => "merchant#reset_password", as: :merchant_reset_password
      patch "merchant/reset-password/:token" => "merchant#reset_password_patch"

      get "merchant/*ignore" => redirect("merchant")
    end

    # Wholesale — private
    scope constraints: lambda { |request| !request.session[:merchant_id].nil? && !Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#index"
      post "merchant" => "merchant#index"
      patch "merchant" => "merchant#update"

      namespace :merchant do
        resources :addresses, except: [:index, :show]
      end

      resource :wholesale, only: [:new, :edit] do
        root to: redirect("/merchant")
        get "product/:id" => "wholesales#edit_product", as: "product"
        patch "update_order/:build_id" => "wholesales#update_order"
        get "checkout" => "wholesales#checkout"
        post "submit" => "wholesales#submit"
        get "order/:id/received" => "wholesales#received", as: "received"
        get "orders" => "wholesales#index"
      end

      get "merchant/*ignore" => redirect("merchant")
    end

    # Admin
    scope constraints: lambda { |request| request.session[:stinker] == ENV.fetch("STINKNAME") } do
      namespace :admin do
        put "builds/:id" => "builds#ajax_update"

        get "totem" => "totem_rows#index", as: "totem"
        resources :totem_rows, except: [:index] do
          resources :totem_items, shallow: true
        end

        resources :products, except: [:show] do
          resources :variations, only: [:new, :create]
          resources :sizes, only: [:new, :create]
        end

        resources :variations, only: [:edit, :update, :destroy] do
          resources :builds, only: [:new, :create]
        end

        resources :builds, only: [:edit, :update, :destroy]
        resources :sizes, only: [:edit, :update, :destroy]
        resources :events, except: [:show]
        resources :locations, except: [:show]

        resources :orders, only: [:index]
        patch "orders/:id/mark-accepted" => "orders#accept", as: :order_mark_accepted
        patch "orders/:id/mark-paid" => "orders#paid", as: :order_mark_paid
        patch "orders/:id/mark-shipped" => "orders#ship", as: :order_mark_shipped

        get "wholesale" => "wholesale#index", as: "wholesale"
      end
    end

    get "*slug" => "static#not_found"
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, :location, { presence: true }
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  def index
    @events = Event.order(updated_at: :desc)
  end
  
  def new
    @model = Event.new
  end
  
  def create
    @model = Event.new(standard_params)
    if @model.save
      redirect_to admin_events_path
    else
      render :new
    end
  end
  
  def edit
    @model = Event.find(params[:id])
  end
  
  def update
    @model = Event.find(params[:id])
    if @model.update(standard_params)
      @model.touch
      redirect_to admin_events_path
    else
      render :edit
    end
  end
  
  def destroy
    render json: Event.find(params[:id]).destroy!
  end
  
private
  
  def standard_params
    params.require(:event).permit :name, :date, :location, :website, :description
  end
  
end

app/views/admin/events/_fields.html.erb
<%= render 'partials/form_errors', model: f.object %>

<div>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :date, "Date" %>
  <%= f.text_field :date %>
</div>

<div>
  <%= f.label :location, "Location" %>
  <%= f.text_field :location %>
</div>

<div>
  <%= f.label :website, "Website" %>
  <%= f.text_field :website %>
</div>

<div>
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, rows: 2 %>
</div>

<hr>

<div class="row spread">
  <% if edit %>
    <div class="perspective right">
      <deleter class="button" path="<%= admin_event_path(f.object) %>" redirect="<%= admin_events_path %>">
        Hold To Delete
      </deleter>
    </div>
  <% end %>
</div>

<hr>

<div class="perspective">
  <%= f.submit "Save", class: "save", data: { disable_with: "Saving" } %>
  <%= link_to "Back", admin_events_path, class: "back" %>
</div>

app/views/admin/events/edit.html.erb
<h1><%= action_name.humanize %> <%= @model.class.name %></h1>

<%= form_for [:admin, @model] do |f| %>
  <%= render "admin/#{controller_name.parameterize}/fields", f: f, edit: action_name == "edit" %>
<% end %>

app/views/admin/events/index.html.erb
<h2 class="perspective">
  <%= link_to "New Event", new_admin_event_path, class: "button" %>
</h2>

<section>
  <% @events.each do |event| %>
    <div class="event">
      <h3 class="bar <%= bar_color %>"><%=event.name%></h3>
      <p><%=event.date.html_safe%></p>
      <p><%=event.location.html_safe%></p>
      <p class="description"><%=event.description.html_safe%></p>
      <% if event.website %><p><a href="<%=event.website%>">Website</a></p><% end %>
      <div class="perspective">
        <%= link_to "Edit", edit_admin_event_path(event), class: "button" %>
      </div>
    </div>
  <% end %>

  <% if @events.empty? %>
    No upcoming events.
  <% end %>
</section>

<p><i>For now, events are sorted by when they were last updated.<br>Open an event and click Save to move it to the front of the list.</i></p>