config/routes.rb
Rails.application.routes.draw do
  scope format: false do
    # MUST COME FIRST: Redirect apex requests to www
    match '(*any)', via: :all, constraints: { subdomain: '' }, to: redirect { |_, req| req.url.sub '//', '//www.' }

    # Retail
    root "totem#index"
    get "checkout" => "static#checkout"
    get "payment" => "static#payment"
    get "order-complete/:id" => "retail_orders#order_complete", as: "order_complete"
    resources :orders, only: [:create, :show], controller: "retail_orders"

    # Static
    get "about" => "static#about"
    get "events" => "static#events"
    get "locations" => "static#locations"
    get "press" => "static#press"
    get "catalog" => "static#catalog"
    get "robots.txt" => "static#robots"

    # Static — Admin
    get "stink" => "static#stink"
    post "stink" => "static#stink_in"
    delete "stink" => "static#stink_out"

    # Tips
    get "tips/double-wrap-belt" => redirect("tips/double-wrap-belt.pdf")

    # Wholesale — both
    get "wholesale/policies" => "wholesales#policies", as: :wholesale_policies
    get "merchant/logout" => "merchant#logout", as: "logout_merchant"
    get "order/:id/invoice" => "wholesales#invoice", as: :wholesale_order_invoice
    post "order/:id/pay" => "wholesales#pay", as: :wholesale_pay_invoice

    # Wholesale — public
    scope constraints: lambda { |request| request.session[:merchant_id].nil? || Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#login"
      post "merchant" => "merchant#login_post"

      get "merchant/check-password" => "merchant#check_password"
      post "merchant/check-password" => "merchant#check_password_post"

      get "merchant/create-password" => "merchant#create_password"
      post "merchant/create-password" => "merchant#create_password_post"

      get "merchant/details" => "merchant#details"
      post "merchant/details" => "merchant#details_post"

      get "merchant/send-password-reset" => "merchant#send_password_reset"
      get "merchant/password-reset-sent" => "merchant#password_reset_sent"

      get "merchant/reset-password/:token" => "merchant#reset_password", as: :merchant_reset_password
      patch "merchant/reset-password/:token" => "merchant#reset_password_patch"

      get "merchant/*ignore" => redirect("merchant")
    end

    # Wholesale — private
    scope constraints: lambda { |request| !request.session[:merchant_id].nil? && !Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#index"
      post "merchant" => "merchant#index"
      patch "merchant" => "merchant#update"

      namespace :merchant do
        resources :addresses, except: [:index, :show]
      end

      resource :wholesale, only: [:new, :edit] do
        root to: redirect("/merchant")
        get "product/:id" => "wholesales#edit_product", as: "product"
        patch "update_order/:build_id" => "wholesales#update_order"
        get "checkout" => "wholesales#checkout"
        post "submit" => "wholesales#submit"
        get "order/:id/received" => "wholesales#received", as: "received"
        get "orders" => "wholesales#index"
      end

      get "merchant/*ignore" => redirect("merchant")
    end

    # Admin
    scope constraints: lambda { |request| request.session[:stinker] == ENV.fetch("STINKNAME") } do
      namespace :admin do
        put "builds/:id" => "builds#ajax_update"

        get "totem" => "totem_rows#index", as: "totem"
        resources :totem_rows, except: [:index] do
          resources :totem_items, shallow: true
        end

        resources :products, except: [:show] do
          resources :variations, only: [:new, :create]
          resources :sizes, only: [:new, :create]
        end

        resources :variations, only: [:edit, :update, :destroy] do
          resources :builds, only: [:new, :create]
        end

        resources :builds, only: [:edit, :update, :destroy]
        resources :sizes, only: [:edit, :update, :destroy]
        resources :events, except: [:show]
        resources :locations, except: [:show]

        resources :orders, only: [:index]
        patch "orders/:id/mark-accepted" => "orders#accept", as: :order_mark_accepted
        patch "orders/:id/mark-paid" => "orders#paid", as: :order_mark_paid
        patch "orders/:id/mark-shipped" => "orders#ship", as: :order_mark_shipped

        get "wholesale" => "wholesale#index", as: "wholesale"
      end
    end

    get "*slug" => "static#not_found"
  end
end

app/controllers/admin/wholesale_controller.rb
class Admin::WholesaleController < ApplicationController
  
  def index
  end
  
end

app/controllers/wholesale/orders_controller.rb
class Wholesale::OrdersController < ApplicationController
  def new
    merchant = Merchant.find(session[:merchant_id])
    if merchant.current_order.nil?
      merchant.current_order = merchant.orders.create!
      merchant.save!
    end
    redirect_to edit_wholesale_order_path
  end
  
  def edit
    @merchant = Merchant.find(session[:merchant_id])
    @kingdoms = Kingdom.all.order(:name)
  end
  
  def edit_product
    @merchant = Merchant.find(session[:merchant_id])
    @product = Product.find(params[:id])
    @builds = @product.builds.joins(:variants).where(variants: { show_wholesale: true })
    @order = @merchant.current_order
  end
  
  def update_product
    merchant = Merchant.find(session[:merchant_id])
    order = merchant.current_order
    builds = params[:builds]
    result = order.update_items builds
    render json: result
  end
  
  def checkout
    
  end
  
end

app/controllers/wholesales_controller.rb
class WholesalesController < ApplicationController
  include MerchantAuth
  prepend_before_action :check_authentication, except: [:invoice, :pay, :policies]

  def index
    @merchant = Merchant.find(session[:merchant_id])
    @orders = @merchant.orders.where.not(submitted: nil).order(created_at: :desc)
  end


  def new
    @merchant = Merchant.find(session[:merchant_id])
    if @merchant.current_order.nil?
      @merchant.current_order = @merchant.orders.create!
      @merchant.save!
    end
    redirect_to edit_wholesale_path
  end


  def edit
    @merchant = Merchant.find(session[:merchant_id])
    @products = Product.order(:name).select { |product| product.builds.any?(&:show_wholesale) }
  end


  def edit_product
    @merchant = Merchant.find(session[:merchant_id])
    @order = @merchant.current_order
    @product = Product.includes(variations: [builds: [:size, :variation, :product]]).find(params[:id])
  end


  def update_order
    @merchant = Merchant.find(session[:merchant_id])
    order = @merchant.current_order
    build = Build.find params[:build_id]
    currency = @merchant.currency
    result = order.update_item_from_build build, params[:quantity], currency
    render json: result
  end


  def checkout
    @merchant = Merchant.includes(current_order: [items: [build: [:variation]]]).find session[:merchant_id]
    @order = @merchant.current_order
    @subtotal = @order.subtotal(@merchant.currency).to_i
    @items_count = @order.items.map(&:quantity).reduce(&:+)
  end


  def submit
    merchant = Merchant.find(session[:merchant_id])
    order = merchant.current_order
    order.orderInfo = wholesale_order_params[:orderInfo] # From Angular
    order.address = merchant.addresses.find wholesale_order_params[:shippingAddressId] # From Angular
    order.submitted = Time.now
    order.save!
    merchant.current_order = nil
    merchant.save!
    Mails.admin_wholesale_order(order).deliver_now
    redirect_to received_wholesale_path order
  end


  def received
    @merchant = Merchant.find(session[:merchant_id])
    @order = @merchant.orders.find_by_uuid(params[:id])
  end


  def invoice
    @order = WholesaleOrder.find_by_uuid(params[:id])
    @merchant = @order.merchant
  end


  def pay
    token = wholesale_order_params[:token] # From JS
    order = WholesaleOrder.find_by_uuid(wholesale_order_params[:id])
    merchant = order.merchant
    currency = merchant.currency
    amount = order.subtotal(currency).to_i # cents
    description = wholesale_order_params[:description] # From HTML

    charge = Stripe::Charge.create(
      source: token,
      amount: amount,
      description: description,
      currency: currency
    )

    order.payment_id = charge.id
    order.paid = Time.now

    order.save!
    order.reload

    merchant.current_order = nil
    merchant.save!

    Mails.admin_wholesale_order_paid(order).deliver_now

    redirect_to wholesale_order_invoice_path(order)

  rescue Stripe::CardError => e
    redirect_to wholesale_order_invoice_path, error: e.message
  end


private


  def wholesale_order_params
    params.permit(:token, :shippingAddressId, :orderInfo, :description, :id)
  end

end

app/views/wholesales/_button_bar.html.erb
<button-bar class="perspective">
  <% if body_id == "edit_product" && body_class == "wholesales" %>
    <%= link_to "< All Products", edit_wholesale_path, class: "back button" %>
  <% end %>
  
  <div ng-cloak ng-show="previewItemsCount > 0">
    <%= link_to "Checkout >", checkout_wholesale_path, class: "button" %>
  </div>
</button-bar>

app/views/wholesales/_wholesale_preview.html.erb
<wholesale-preview>
  <div class="sticky">
    <div class="nav" ng-class="{invisible:previewItemsCount == 0}">
      <div class="perspective">
        <%= link_to "Checkout >", checkout_wholesale_path, class: "button" %>
      </div>
    </div>

    <script>
      FEHU.orderItems = <%= preview_order_items_json(@merchant.current_order) %>
    </script>

    <h1>In Your Order</h1>
    <h3 class="appear" ng-hide="true">Loading...</h3>
    <h3 class="appear" ng-hide="previewItemsCount > 0">Nothing yet...</h3>
    <div class="items" ng-cloak ng-controller="PreviewCtrl">
      <div ng-repeat="item in sortedPreviewItems">
        <a class="item" ng-href="/wholesale/product/{{item.product_id}}">
          <img class="preview" ng-src="{{item.image}}">
          <span class="details">
            <span class="name">{{item.build_name}}</span>
            <span class="price">
              {{ item.quantity }} for ${{ item.quantity * item.prices["<%= @merchant.currency %>"] }}
            </span>
          </span>
        </a>
        <a class="remove" ng-click="remove(item)">
          Remove
        </a>
      </div>
      <h3 class="appear" ng-show="updatingItems">Updating...</h3>
    </div>
  </div>
</wholesale-preview>

app/views/wholesales/checkout.html.erb
<h1>It's Checkout Time</h1>

<section>
  <h3>You're about to order <%= link_to "#{@items_count} item".pluralize(@items_count), edit_wholesale_path %> for $<%=@subtotal%> <%= @merchant.currency %></h3>

  <div class="little-preview">
    <% @order.items.each do |item| %>
      <% item.quantity.times do %>
        <div>
          <%= image_tag item.build.variation.wholesale_image if item.build.variation.wholesale_image %>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

<section ng-cloak>
  <h2>Where should we ship it to?</h2>
  <div class="addresses">
    <% if @merchant.addresses.length > 0 %>
      <div ng-init="shipTo = <%=@merchant.addresses.first.id%>"></div>
      <% @merchant.addresses.each do |address| %>
        <div class="address" ng-click="shipTo = <%=address.id%>; email = '<%=address.email%>'" ng-class="{selected:shipTo == <%=address.id%>}">
          <div class="info">
            <%= address.name %><br>
            <%= address.line1 %><br>
            <% if address.line2.present? %>
              <%= address.line2 %><br>
            <% end %>
            <%= address.city %>, <%= address.region %><br>
            <%= address.code %> <%= address.country %>
          </div>
          <div class="edit">
            <%= link_to "Edit", edit_merchant_address_path(address) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="perspective center">
    <%= link_to "New Address", new_merchant_address_path, class: "button" %>
  </div>
</section>

<section ng-cloak ng-show="shipTo != null">
  <label class="preferedDate">
    Preferred delivery date (optional, best effort)
    <input ng-model="order.preferredDate" type="text">
  </label>
  <label class="notes">
    Notes (optional)
    <textarea ng-model="order.notes"></textarea>
  </label>
</section>

<section ng-cloak ng-show="shipTo" class="submit center">
  <%= form_tag submit_wholesale_path, class: "inbl perspective" do |f| %>
    <input type="hidden" name="shippingAddressId" value="{{shipTo | json}}">
    <input type="hidden" name="orderInfo" value="{{order | json}}">
    <input type="submit" value="Submit Order">
  <% end %>
  <br>
  <br>
  <p>We will review the order, then email you an invoice.</p>
</section>

app/views/wholesales/edit.html.erb
<div class="split">
  <wholesale-builder>
    <div class="nav perspective">
      <a class="invisible button">I am invisible!</a>
    </div>

    <h1>Add a Product to Your Order</h1>
    <div class="products">
      <% @products.each do |product| %>
        <a class="product" href="<%= product_wholesale_path(product.id) %>">
          <img src="<%=product.wholesale_image%>">
          <span><%= product.name %></span>
        </a>
      <% end %>
    </div>
  </wholesale-builder>

  <%= render "wholesales/wholesale_preview" %>

</div>

app/views/wholesales/edit_product.html.erb
<div class="top">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewbox="20 40 160 140">
    <defs>
      <path id="svg-circle" d="M25, 100 a75,75 0 1,0 150,0 a75,75 0 1,0 -150,0"/>
      <clipPath id="clip-path"><path d="M40, 100 a60,60 0 1,1 120,0 a60,60 0 1,1 -120,0"/></clipPath>
    </defs>
    <image x="40" y="40" width="120" height="120" xlink:href="<%=@product.totem_image%>" clip-path='url(#clip-path)' />
    <text x="0" y="0" fill="#456" fill-opacity="1" transform="rotate(<%=-90 + @product.name.length*3%>, 100, 100)">
      <textPath xlink:href="#svg-circle"><%= @product.name %></textPath>
    </text>
  </svg>

  <div class="info">
    <div class="overview">
      <%= @product.description_wholesale.html_safe %>
    </div>
  </div>
</div>

<div class="split">
  <div class="variations">
    <div class="nav glass sticky">
      <div class="perspective">
        <%= link_to "< All Products", edit_wholesale_path, class: "back button" %>
      </div>
    </div>

    <h1>Add to Your Order</h1>
    <% @product.variations.select(&:show_wholesale).each do |variation| %>
      <div class="variation">
        <div class="info">
          <span class="name">
            <%= variation.name %>
          </span>
          <span class="price">
            $<%= (variation.price_wholesale_render(@merchant.currency)/100.0).round %>
          </span>
        </div>
        <%= image_tag variation.wholesale_image, class: "variation-image" if variation.wholesale_image %>
        <div class="builds">
          <% variation.builds.where(show_wholesale: true).each do |build| %>
            <div ng-cloak class="build" item-editor>
              <div class="quantity">
                <span class="size-name"><%= build.size.name %></span>
                <div class="pill perspective">
                  <input type="number"
                         ng-model="editorBuild.displayQuantity"
                         ng-change="changeQuantity()"
                         ng-blur="blurQuantity()"
                         ng-init="initQuantity(<%= current_order_quantity(@order, build) %>)">
                  <div class="button" ng-click="adjustQuantity(-1)">-</div>
                  <div class="button" ng-click="adjustQuantity(1)">+</div>
                  <div class="button five" ng-click="adjustQuantity(5)">+5</div>
                </div>
              </div>
              <span ng-init="editorBuild.build_id=<%= build.id %>"></span>
              <span ng-init="editorBuild.product_id='<%= @product.id %>'"></span>
              <span ng-init="editorBuild.product_name='<%= @product.name %>'"></span>
              <span ng-init="editorBuild.size_name='<%= build.size.name %>'"></span>
              <span ng-init="editorBuild.variation_name='<%= variation.name %>'"></span>
              <span ng-init="editorBuild.prices=<%= build.wholesale_prices.to_json %>"></span>
              <span ng-init="editorBuild.image='<%= variation.wholesale_image %>'"></span>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= render "wholesales/wholesale_preview" %>
</div>

app/views/wholesales/index.html.erb
<h1>Past Orders</h1>

<section class="center">
  <% if @merchant.orders.count == 0 %>
    <h3 class="center">
      None yet. Would you like to
      <% if @merchant.current_order.nil? %>
        <%= link_to "place a new order", new_wholesale_path %>?
      <% else %>
        <%= link_to "edit your current order", edit_wholesale_path %>?
      <% end %>
    </h3>
  <% end %>

  <table>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <b><%= pluralize order.items.count, "Item" %></b>
          ordered on <b><%= order.submitted.strftime("%B %d, %Y") %></b>
          for <b>$<%= PrintMoney.cents_to_dollars(order.subtotal(@merchant.currency)) %></b>
        </td>
        <td><%= order.paid.present? ? "Paid on #{order.paid.strftime("%B %d, %Y")}" : "Not Paid" %></td>
        <td><%= link_to "View Invoice", wholesale_order_invoice_path(order) %></td>
      </tr>
    <% end %>
  </table>
</section>

app/views/wholesales/invoice.html.erb
<h3 class="center">Wholesale Order Invoice</h3>

<section>
  <p>
    <h4>Shipping Address</h4>
    <%= @order.address.line1 %><br>
    <% if @order.address.line2.present? %>
      <%= @order.address.line2 %><br>
    <% end %>
    <%= @order.address.region %>
    <%= @order.address.code %><br>
    <%= @order.address.country %>
  </p>
</section>

<section>
  <table>
    <tr>
      <th>Product</th>
      <th>Variation</th>
      <th>Quantity</th>
      <th></th>
    </tr>
    <% @order.items.each do |item| %>
      <tr>
        <td><%= item.product_name %></td>
        <td><%= item.build_name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
    <tr>
      <td>Subtotal</td>
      <td></td>
      <td></td>
      <td><%= PrintMoney.cents_to_dollars(@order.subtotal(@merchant.currency)) %>
    </tr>
    <tr>
      <td>GST</td>
      <td></td>
      <td></td>
      <td><%= PrintMoney.cents_to_dollars((0.05 * @order.subtotal(@merchant.currency)).round) %></td>
    </tr>
    <tr>
      <td><b>Total</b></td>
      <td></td>
      <td></td>
      <td><b><%= PrintMoney.cents_to_dollars((1.05 * @order.subtotal(@merchant.currency)).round) %></b></td>
    </tr>
  </table>
</section>

<section class="payment">
  <% if @order.paid.present? %>
    <h3>Paid on <%= @order.paid.strftime("%B %d, %Y") %></h3>
  <% else %>
    <%= form_tag wholesale_pay_invoice_path(@order.uuid), class: "stripe" do |f| %>
      <input type="hidden" name="email" value="<%=merchant.email%>">
      <input type="hidden" name="subtotal" value="<%=@order.subtotal(merchant.currency)%>">
      <input type="hidden" name="currency" value="<%=@merchant.currency%>">
      <input type="hidden" name="description" value="<%=@order.description%>">

      <script src="https://checkout.stripe.com/checkout.js"></script>
      <div class="perspective">
        Payment is due prior to shipping.
        You may
        <button>Pay with Card</button>,
        send an e-Transfer to freyja@fehuleather.com with the password "cufflove",
        or mail a cheque.
      </div>
    <% end %>
  <% end %>
</section>

<section class="actions">
  <%= link_to "Wholesale Policies", wholesale_policies_path %>
</section>

app/views/wholesales/policies.html.erb
<div class="primary row clear">
  <div class="row">
    <h2 class="col col3">Payment</h2>
    <div class="col col6">
      <h3>Payment Methods</h3>
      <p>
        Credit Card, e-Transfer, Cheque
      </p>
      <h3>Payment Terms</h3>
      <p>
        Payment is due before shipping.<br>
        <br>
        Net 30 is available upon request.
      </p>
    </div>
  </div>
  <hr>
  <div class="row">
    <h2 class="col col3">Minimums</h2>

    <div class="col col6">
      <h3>First Order Minimum</h3>
      <p>$100.00</p>
      <h3>Re-order Minimum</h3>
      <p>$100.00</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <h2 class="col col3">Shipping</h2>
    <div class="col col6">
      <h3>Shipping Method</h3>
      <p>FOB Origin (Red Deer, Alberta, Canada).<br>
        <br>
        Canada Post is our preferred carrier. We are also happy to ship with DHL or FedEx, at your discretion. Additionally, you are welcome to use your own account to pay for shipping.<br>
      </p>

      <h3>Drop Shipping</h3>
      <p>
        Drop shipping available on request.
      </p>

      <h3>Shipping Cost</h3>
      <p>We offer flat rate shipping for $15 within Canada and $25 within the US, when shipping with Canada Post, .</p>

      <h3>Estimated Production Time</h3>
      <p>3 weeks</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col col6 col-offset3">
      <h3>Product Customization</h3>
      <p>
        Accepts customization requests.
      </p>
      <h3>Returns, Damages, and Repairs</h3>
      <p>Returns &amp; Refunds<br>
        It is of the utmost importance that you are thrilled with the products you receive. As such, I want to give you ample opportunity to get to know my products and make sure that they are a good fit for your store. I offer a no-questions-asked return policy for the first 8 weeks. After 8 weeks I am happy to exchange products, but I'll ask that you cover shipping both ways.
      </p>
    </div>
  </div>
</div>

app/views/wholesales/received.html.erb
<h2 class="center">Your Order Has Been Placed</h2>

<p>Thank you! We'll review the order, and then email you an invoice in a day or two.</p>

<hr>

<h3>Order Summary</h3>

<section>
  <p>
    <h4>Shipping Address</h4>
    <%= @order.address.line1 %><br>
    <% if @order.address.line2.present? %>
      <%= @order.address.line2 %><br>
    <% end %>
    <%= @order.address.region %>
    <%= @order.address.code %><br>
    <%= @order.address.country %>
  </p>
</section>

<section>
  <table>
    <tr>
      <th>Product</th>
      <th>Variation</th>
      <th>Quantity</th>
      <th></th>
    </tr>
    <% @order.items.each do |item| %>
      <tr>
        <td><%= item.product_name %></td>
        <td><%= item.build_name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
    <tr>
      <td>Subtotal</td>
      <td></td>
      <td></td>
      <td><%= PrintMoney.cents_to_dollars(@order.subtotal(@merchant.currency)) %></td>
    </tr>
    <tr>
      <td>GST</td>
      <td></td>
      <td></td>
      <td><%= PrintMoney.cents_to_dollars((0.05 * @order.subtotal(@merchant.currency)).round) %></td>
    </tr>
    <tr>
      <td><b>Total</b></td>
      <td></td>
      <td></td>
      <td><b><%= PrintMoney.cents_to_dollars((1.05 * @order.subtotal(@merchant.currency)).round) %></b></td>
    </tr>
  </table>
</section>

app/views/wholesales/show.html.erb
<h3 class="center">Wholesale Order Invoice</h3>

<section>
  <p>
    <h4>Shipping Address</h4>
    <%= @order.address.line1 %><br>
    <% if @order.address.line2.present? %>
      <%= @order.address.line2 %><br>
    <% end %>
    <%= @order.address.region %>
    <%= @order.address.code %><br>
    <%= @order.address.country %>
  </p>
</section>

<section>
  <table>
    <tr>
      <th>Product</th>
      <th>Variation</th>
      <th>Quantity</th>
      <th></th>
    </tr>
    <% @order.items.each do |item| %>
      <tr>
        <td><%= item.product_name %></td>
        <td><%= item.build_name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
      </tr>
    <% end %>
    <tr>
      <td>Subtotal</td>
      <td></td>
      <td></td>
      <td><%= PrintMoney.cents_to_dollars(@order.subtotal("CAD")) %><!-- TODO: Currency --></td>
    </tr>
    <tr>
      <td>GST</td>
      <td></td>
      <td></td>
      <td><%= PrintMoney.cents_to_dollars((0.05 * @order.subtotal("CAD")).round) %><!-- TODO: Currency --></td>
    </tr>
    <tr>
      <td><b>Total</b></td>
      <td></td>
      <td></td>
      <td><b><%= PrintMoney.cents_to_dollars((1.05 * @order.subtotal("CAD")).round) %><!-- TODO: Currency --></b></td>
    </tr>
  </table>
</section>

<section>
  <%= form_tag pay_wholesale_path, class: "stripe" do |f| %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <div class="perspective">
      Payment is due prior to shipping.
      You may
      <button>Pay with Card</button>,
      send an e-Transfer to freyja@fehuleather.com with the password "cufflove",
      or mail a cheque.
    </div>
  <% end %>
</section>

<section>
  <%= form_tag share_wholesale_path do %>
    <h3>Share this invoice.</h3>

    <%= label_tag :email do %>
      <%= hidden_field_tag :order_id, @order.id %>
      Recipient's Email
      <%= email_field_tag :email %>
    <% end %>

    <div class="share perspective">
      <%= submit_tag "Send", class: "save", data: { disable_with: 'Sending' } %>
    </div>
  <% end %>
</section>