config/routes.rb
Rails.application.routes.draw do
  scope format: false do
    # MUST COME FIRST: Redirect apex requests to www
    match '(*any)', via: :all, constraints: { subdomain: '' }, to: redirect { |_, req| req.url.sub '//', '//www.' }

    # Retail
    root "totem#index"
    get "checkout" => "static#checkout"
    get "payment" => "static#payment"
    get "order-complete/:id" => "retail_orders#order_complete", as: "order_complete"
    resources :orders, only: [:create, :show], controller: "retail_orders"

    # Static
    get "about" => "static#about"
    get "events" => "static#events"
    get "locations" => "static#locations"
    get "press" => "static#press"
    get "catalog" => "static#catalog"
    get "robots.txt" => "static#robots"

    # Static — Admin
    get "stink" => "static#stink"
    post "stink" => "static#stink_in"
    delete "stink" => "static#stink_out"

    # Tips
    get "tips/double-wrap-belt" => redirect("tips/double-wrap-belt.pdf")

    # Wholesale — both
    get "wholesale/policies" => "wholesales#policies", as: :wholesale_policies
    get "merchant/logout" => "merchant#logout", as: "logout_merchant"
    get "order/:id/invoice" => "wholesales#invoice", as: :wholesale_order_invoice
    post "order/:id/pay" => "wholesales#pay", as: :wholesale_pay_invoice

    # Wholesale — public
    scope constraints: lambda { |request| request.session[:merchant_id].nil? || Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#login"
      post "merchant" => "merchant#login_post"

      get "merchant/check-password" => "merchant#check_password"
      post "merchant/check-password" => "merchant#check_password_post"

      get "merchant/create-password" => "merchant#create_password"
      post "merchant/create-password" => "merchant#create_password_post"

      get "merchant/details" => "merchant#details"
      post "merchant/details" => "merchant#details_post"

      get "merchant/send-password-reset" => "merchant#send_password_reset"
      get "merchant/password-reset-sent" => "merchant#password_reset_sent"

      get "merchant/reset-password/:token" => "merchant#reset_password", as: :merchant_reset_password
      patch "merchant/reset-password/:token" => "merchant#reset_password_patch"

      get "merchant/*ignore" => redirect("merchant")
    end

    # Wholesale — private
    scope constraints: lambda { |request| !request.session[:merchant_id].nil? && !Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#index"
      post "merchant" => "merchant#index"
      patch "merchant" => "merchant#update"

      namespace :merchant do
        resources :addresses, except: [:index, :show]
      end

      resource :wholesale, only: [:new, :edit] do
        root to: redirect("/merchant")
        get "product/:id" => "wholesales#edit_product", as: "product"
        patch "update_order/:build_id" => "wholesales#update_order"
        get "checkout" => "wholesales#checkout"
        post "submit" => "wholesales#submit"
        get "order/:id/received" => "wholesales#received", as: "received"
        get "orders" => "wholesales#index"
      end

      get "merchant/*ignore" => redirect("merchant")
    end

    # Admin
    scope constraints: lambda { |request| request.session[:stinker] == ENV.fetch("STINKNAME") } do
      namespace :admin do
        put "builds/:id" => "builds#ajax_update"

        get "totem" => "totem_rows#index", as: "totem"
        resources :totem_rows, except: [:index] do
          resources :totem_items, shallow: true
        end

        resources :products, except: [:show] do
          resources :variations, only: [:new, :create]
          resources :sizes, only: [:new, :create]
        end

        resources :variations, only: [:edit, :update, :destroy] do
          resources :builds, only: [:new, :create]
        end

        resources :builds, only: [:edit, :update, :destroy]
        resources :sizes, only: [:edit, :update, :destroy]
        resources :events, except: [:show]
        resources :locations, except: [:show]

        resources :orders, only: [:index]
        patch "orders/:id/mark-accepted" => "orders#accept", as: :order_mark_accepted
        patch "orders/:id/mark-paid" => "orders#paid", as: :order_mark_paid
        patch "orders/:id/mark-shipped" => "orders#ship", as: :order_mark_shipped

        get "wholesale" => "wholesale#index", as: "wholesale"
      end
    end

    get "*slug" => "static#not_found"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :merchant # Optional — will be nil if this is a retail order
  has_many :items, class_name: OrderItem, dependent: :destroy
  
  def item_for_build(build)
    items.where(build_id: build.id).first
  end
  
  def create_item_for_build(build, isWholesale)
    item = items.new build_id: build.id
    item.build = build
    item.build_name = build.build_name
    item.product_name = build.product.name
    item.cents = isWholesale ? build.price_wholesale : build.price_retail
    item.save!
    item
  end
  
  def update_item_from_build(build, quantity, isWholesale)
    if quantity > 0
      item = item_for_build(build) || create_item_for_build(build, isWholesale)
      item.quantity = quantity
      item.save! # Will error if this fails, which is what we want
      item.quantity
    else
      item = item_for_build(build)
      item.destroy! if item.present?
      0 # We now have 0 quantity
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    retail = RetailOrder.includes(:items).group_by { |order| order.created_at.strftime("%B %d, %Y") }
    wholesale = WholesaleOrder.includes(:items).where.not(address: nil).group_by { |order| order.submitted.strftime("%B %d, %Y") }
    @orders_by_date = retail.merge(wholesale) {|k, a, b| a + b }
  end

  def accept
    order = WholesaleOrder.find(params[:id])
    order.accepted = Time.now
    if order.save
      Mails.wholesale_order_accepted(order).deliver_now
      redirect_to admin_orders_path
    else
      redirect_to admin_orders_path, notice: order.errors.full_messages.first
    end
  end

  def ship
    is_wholesale = params[:wholesale] == "true"
    order = (is_wholesale ? WholesaleOrder : RetailOrder).find(params[:id])

    order.shipped = Time.now
    order.tracking_number = params[:tracking_number]
    if order.save

      # TODO: Email confirmation for shipped retail orders
      (is_wholesale ? Mails.wholesale_order_shipped(order) : nil).deliver_now

      redirect_to admin_orders_path
    else
      redirect_to admin_orders_path, notice: order.errors.full_messages.first
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end
  
  def create
    builds_data = JSON.parse order_params[:builds] # From JS
    notes = order_params[:notes] # From Angular
    quantity = order_params[:quantity].to_i # From JS
    shippingAddress = JSON.parse order_params[:shippingAddress] # From Angular
    token = order_params[:token] # From JS
    
    builds = builds_data.map { |id, q| Build.find(id) }
    
    amount = builds.map(&:price_retail).reduce(0, :+) # In cents
    description = "#{quantity} Item #{quantity == 1 ? "" : "s"} from Fehu Inc."
    
    charge = Stripe::Charge.create(
      source: token,
      amount: amount,
      description: description,
      currency: "CAD"
    )
    
    order = Order.new(
      notes: notes
    )
    
    builds.each do |build|
      order.items.new(
        build: build,
        build_name: build.build_name,
        product_name: build.product.name,
        price: build.variation.price_retail,
        quantity: builds_data[build.id.to_s]
      )
    end
    
    order.save!
    
    # Email Freyja
    
    redirect_to order_path(order)
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to payment_path
  end
  
private
  
  def order_params
    params.permit(:token, :builds, :shippingAddress, :notes)
  end

end

app/controllers/wholesale/orders_controller.rb
class Wholesale::OrdersController < ApplicationController
  def new
    merchant = Merchant.find(session[:merchant_id])
    if merchant.current_order.nil?
      merchant.current_order = merchant.orders.create!
      merchant.save!
    end
    redirect_to edit_wholesale_order_path
  end
  
  def edit
    @merchant = Merchant.find(session[:merchant_id])
    @kingdoms = Kingdom.all.order(:name)
  end
  
  def edit_product
    @merchant = Merchant.find(session[:merchant_id])
    @product = Product.find(params[:id])
    @builds = @product.builds.joins(:variants).where(variants: { show_wholesale: true })
    @order = @merchant.current_order
  end
  
  def update_product
    merchant = Merchant.find(session[:merchant_id])
    order = merchant.current_order
    builds = params[:builds]
    result = order.update_items builds
    render json: result
  end
  
  def checkout
    
  end
  
end

app/views/admin/orders/index.html.erb
<h1>Orders</h1>

<% @orders_by_date.each do |date, orders| %>
  <h3><%= date %></h3>
  <% orders.each do |order| %>
    <div class="order <%= order.class.to_s %>">
      <div class="type"><%= order.class.to_s.slice(0) %></div>
      <div class="name"><%= order.address.name %></div>
      <div class="line1"><%= order.address.line1 %></div>
      <% if order.address.line2.present? %>
        <div class="line2"><%= order.address.line2 %></div>
      <% end %>
      <div>
        <span class="city"><%= order.address.city %></span>,
        <span class="region"><%= order.address.region %></span>
      </div>
      <div class="code"><%= order.address.code %></div>
      <div class="country"><%= order.address.country %></div>
      <div class="email"><%= order.address.email %></div>
      <table class="items">
        <% order.items.each do |item| %>
        <tr class="item">
          <td class="quantity"><%= item.quantity %></td>
          <td class="build"><%= item.build_name %></td>
          <td class="product"><%= item.product_name %></td>
          <!-- <td>
            <label>
              <input type="checkbox" name="<%=item.id%>">
              Ready To Go
            </label>
          </td> -->
        </tr>
        <% end %>
      </table>

      <hr>

      <% if order.wholesale? %>
        <% if order.accepted.present? %>
          <h3>Accepted on <%= order.accepted.strftime("%B %d, %Y") %></h3>
        <% else %>
          <div>
            <div class="perspective">
              <%= link_to "Accept Order", admin_order_mark_accepted_path(order.id), method: :patch, class: "button" %>
            </div>
          </div>
        <% end %>

        <% if order.accepted.present? %>
          <hr>
          <% if order.paid.present? %>
            <h3>Paid on <%= order.paid.strftime("%B %d, %Y") %></h3>
          <% else %>
            <h3>Not yet paid.</h3>
            <div class="perspective">
              <%= link_to "Mark as Paid", admin_order_mark_paid_path(order.id), method: :patch, class: "button" %>
            </div>
          <% end %>
        <% end %>
      <% end %>

      <% if order.paid.present? || order.accepted.present? %>
        <hr>

        <% if order.shipped.present? %>
          <h3>Shipped on <%= order.shipped.strftime("%B %d, %Y") %> with tracking number <%= order.tracking_number %></h3>
        <% else %>
          <%= form_for order, url: admin_order_mark_shipped_path(order.id), method: :patch do |f| %>
            <%= f.hidden_field_tag :wholesale, order.wholesale?.to_s %>
            <div>
              <%= f.label :tracking_number, "Tracking Number" %>
              <%= f.text_field :tracking_number %>
            </div>
            <div class="perspective">
              <%= f.submit "Mark as Shipped", class: "save", data: { disable_with: "Marking..." } %>
            </div>
          <% end %>
        <% end %>
      <% end %>

    </div>
  <% end %>
<% end %>