config/routes.rb
Rails.application.routes.draw do
  scope format: false do
    # MUST COME FIRST: Redirect apex requests to www
    match '(*any)', via: :all, constraints: { subdomain: '' }, to: redirect { |_, req| req.url.sub '//', '//www.' }

    # Retail
    root "totem#index"
    get "checkout" => "static#checkout"
    get "payment" => "static#payment"
    get "order-complete/:id" => "retail_orders#order_complete", as: "order_complete"
    resources :orders, only: [:create, :show], controller: "retail_orders"

    # Static
    get "about" => "static#about"
    get "events" => "static#events"
    get "locations" => "static#locations"
    get "press" => "static#press"
    get "catalog" => "static#catalog"
    get "robots.txt" => "static#robots"

    # Static — Admin
    get "stink" => "static#stink"
    post "stink" => "static#stink_in"
    delete "stink" => "static#stink_out"

    # Tips
    get "tips/double-wrap-belt" => redirect("tips/double-wrap-belt.pdf")

    # Wholesale — both
    get "wholesale/policies" => "wholesales#policies", as: :wholesale_policies
    get "merchant/logout" => "merchant#logout", as: "logout_merchant"
    get "order/:id/invoice" => "wholesales#invoice", as: :wholesale_order_invoice
    post "order/:id/pay" => "wholesales#pay", as: :wholesale_pay_invoice

    # Wholesale — public
    scope constraints: lambda { |request| request.session[:merchant_id].nil? || Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#login"
      post "merchant" => "merchant#login_post"

      get "merchant/check-password" => "merchant#check_password"
      post "merchant/check-password" => "merchant#check_password_post"

      get "merchant/create-password" => "merchant#create_password"
      post "merchant/create-password" => "merchant#create_password_post"

      get "merchant/details" => "merchant#details"
      post "merchant/details" => "merchant#details_post"

      get "merchant/send-password-reset" => "merchant#send_password_reset"
      get "merchant/password-reset-sent" => "merchant#password_reset_sent"

      get "merchant/reset-password/:token" => "merchant#reset_password", as: :merchant_reset_password
      patch "merchant/reset-password/:token" => "merchant#reset_password_patch"

      get "merchant/*ignore" => redirect("merchant")
    end

    # Wholesale — private
    scope constraints: lambda { |request| !request.session[:merchant_id].nil? && !Merchant.find_by_id(request.session[:merchant_id]).nil? } do
      get "merchant" => "merchant#index"
      post "merchant" => "merchant#index"
      patch "merchant" => "merchant#update"

      namespace :merchant do
        resources :addresses, except: [:index, :show]
      end

      resource :wholesale, only: [:new, :edit] do
        root to: redirect("/merchant")
        get "product/:id" => "wholesales#edit_product", as: "product"
        patch "update_order/:build_id" => "wholesales#update_order"
        get "checkout" => "wholesales#checkout"
        post "submit" => "wholesales#submit"
        get "order/:id/received" => "wholesales#received", as: "received"
        get "orders" => "wholesales#index"
      end

      get "merchant/*ignore" => redirect("merchant")
    end

    # Admin
    scope constraints: lambda { |request| request.session[:stinker] == ENV.fetch("STINKNAME") } do
      namespace :admin do
        put "builds/:id" => "builds#ajax_update"

        get "totem" => "totem_rows#index", as: "totem"
        resources :totem_rows, except: [:index] do
          resources :totem_items, shallow: true
        end

        resources :products, except: [:show] do
          resources :variations, only: [:new, :create]
          resources :sizes, only: [:new, :create]
        end

        resources :variations, only: [:edit, :update, :destroy] do
          resources :builds, only: [:new, :create]
        end

        resources :builds, only: [:edit, :update, :destroy]
        resources :sizes, only: [:edit, :update, :destroy]
        resources :events, except: [:show]
        resources :locations, except: [:show]

        resources :orders, only: [:index]
        patch "orders/:id/mark-accepted" => "orders#accept", as: :order_mark_accepted
        patch "orders/:id/mark-paid" => "orders#paid", as: :order_mark_paid
        patch "orders/:id/mark-shipped" => "orders#ship", as: :order_mark_shipped

        get "wholesale" => "wholesale#index", as: "wholesale"
      end
    end

    get "*slug" => "static#not_found"
  end
end

app/controllers/admin/wholesale_controller.rb
class Admin::WholesaleController < ApplicationController
  
  def index
  end
  
end

app/controllers/wholesale/orders_controller.rb
class Wholesale::OrdersController < ApplicationController
  def new
    merchant = Merchant.find(session[:merchant_id])
    if merchant.current_order.nil?
      merchant.current_order = merchant.orders.create!
      merchant.save!
    end
    redirect_to edit_wholesale_order_path
  end
  
  def edit
    @merchant = Merchant.find(session[:merchant_id])
    @kingdoms = Kingdom.all.order(:name)
  end
  
  def edit_product
    @merchant = Merchant.find(session[:merchant_id])
    @product = Product.find(params[:id])
    @builds = @product.builds.joins(:variants).where(variants: { show_wholesale: true })
    @order = @merchant.current_order
  end
  
  def update_product
    merchant = Merchant.find(session[:merchant_id])
    order = merchant.current_order
    builds = params[:builds]
    result = order.update_items builds
    render json: result
  end
  
  def checkout
    
  end
  
end

app/controllers/wholesales_controller.rb
class WholesalesController < ApplicationController
  include MerchantAuth
  prepend_before_action :check_authentication, except: [:invoice, :pay, :policies]

  def index
    @merchant = Merchant.find(session[:merchant_id])
    @orders = @merchant.orders.where.not(submitted: nil).order(created_at: :desc)
  end


  def new
    @merchant = Merchant.find(session[:merchant_id])
    if @merchant.current_order.nil?
      @merchant.current_order = @merchant.orders.create!
      @merchant.save!
    end
    redirect_to edit_wholesale_path
  end


  def edit
    @merchant = Merchant.find(session[:merchant_id])
    @products = Product.order(:name).select { |product| product.builds.any?(&:show_wholesale) }
  end


  def edit_product
    @merchant = Merchant.find(session[:merchant_id])
    @order = @merchant.current_order
    @product = Product.includes(variations: [builds: [:size, :variation, :product]]).find(params[:id])
  end


  def update_order
    @merchant = Merchant.find(session[:merchant_id])
    order = @merchant.current_order
    build = Build.find params[:build_id]
    currency = @merchant.currency
    result = order.update_item_from_build build, params[:quantity], currency
    render json: result
  end


  def checkout
    @merchant = Merchant.includes(current_order: [items: [build: [:variation]]]).find session[:merchant_id]
    @order = @merchant.current_order
    @subtotal = @order.subtotal(@merchant.currency).to_i
    @items_count = @order.items.map(&:quantity).reduce(&:+)
  end


  def submit
    merchant = Merchant.find(session[:merchant_id])
    order = merchant.current_order
    order.orderInfo = wholesale_order_params[:orderInfo] # From Angular
    order.address = merchant.addresses.find wholesale_order_params[:shippingAddressId] # From Angular
    order.submitted = Time.now
    order.save!
    merchant.current_order = nil
    merchant.save!
    Mails.admin_wholesale_order(order).deliver_now
    redirect_to received_wholesale_path order
  end


  def received
    @merchant = Merchant.find(session[:merchant_id])
    @order = @merchant.orders.find_by_uuid(params[:id])
  end


  def invoice
    @order = WholesaleOrder.find_by_uuid(params[:id])
    @merchant = @order.merchant
  end


  def pay
    token = wholesale_order_params[:token] # From JS
    order = WholesaleOrder.find_by_uuid(wholesale_order_params[:id])
    merchant = order.merchant
    currency = merchant.currency
    amount = order.subtotal(currency).to_i # cents
    description = wholesale_order_params[:description] # From HTML

    charge = Stripe::Charge.create(
      source: token,
      amount: amount,
      description: description,
      currency: currency
    )

    order.payment_id = charge.id
    order.paid = Time.now

    order.save!
    order.reload

    merchant.current_order = nil
    merchant.save!

    Mails.admin_wholesale_order_paid(order).deliver_now

    redirect_to wholesale_order_invoice_path(order)

  rescue Stripe::CardError => e
    redirect_to wholesale_order_invoice_path, error: e.message
  end


private


  def wholesale_order_params
    params.permit(:token, :shippingAddressId, :orderInfo, :description, :id)
  end

end

app/views/wholesale/index.html.erb
<h1 class="page-title">Wholesale</h1>

<section class="actions">
  <% if @merchant.current_order.nil? %>
    <a href="/wholesale/order/new">New Order</a>
  <% else %>
    <a href="/wholesale/order/edit">Edit Current Order</a>
  <% end %>
  <a href="/wholesale/order/repeat">Quick Re-Order</a>
  <a href="/wholesale/orders">View Past Orders</a>
  <a href="/wholesale/line-sheet">Download/Print Line Sheet</a>
</section>

<section>
  <%= form_for @merchant, url: merchant_path do |f| %>
    <p>Need to update your contact info?</p>
    
    <%= render 'partials/form_errors', model: @merchant %>
    
    <div class="fields">
    
      <div class="field">
        <label>
          Your Name
          <div class="info-prompt" toggler-toggle="OwnerName">?</div>
          <%= f.text_field :your_name, placeholder: "eg: Tyr Annosaurus" %>
        </label>
      </div>
      
      <div class="field">
        <label>
          Store Name
          <div class="info-prompt" toggler-toggle="StoreName">?</div>
          <%= f.text_field :store_name, placeholder: "eg: Tiny Arms Apparel" %>
        </label>
      </div>

      <div class="field">
        <label>
          Email Address
          <div class="info-prompt" toggler-toggle="Email">?</div>
          <%= f.text_field :email, placeholder: "eg: its-me@example.com" %>
        </label>
      </div>
        
      <div class="field">
        <label>
          Phone Number
          <div class="info-prompt" toggler-toggle="OwnerPhone">?</div>
          <%= f.text_field :phone_number, placeholder: "eg: (006) 500-0000" %>
        </label>
      </div>
      
    </div>
        
    <hr>
      
    <div class="perspective">
      <%= f.submit "Save" %>
    </div>

  <% end %>

  <div class="info-popup" toggler-target="StoreName">
    If you represent multiple stores or locations, just enter the name of the overall brand.
    <div class="close" toggler-hide="StoreName">Close</div>
  </div>

  <div class="info-popup" toggler-target="OwnerName">
    If we need to follow up with you about this order, it helps to know who placed the order.
    <div class="close" toggler-hide="OwnerName">Close</div>
  </div>

  <div class="info-popup" toggler-target="OwnerPhone">
    We will try to reach you by email. If that fails, we'll try this number.
    <div class="close" toggler-hide="OwnerPhone">Close</div>
  </div>

  <div class="info-popup" toggler-target="Email">
    We'll store your account info under this email address. We'll also use it as the main contact address for your account.
    <div class="close" toggler-hide="Email">Close</div>
  </div>
</section>

app/views/wholesale/login.html.erb
<h1 class="page-title">Bring Some Fehu Into Your Store</h1>

<p>In just a moment, you'll be able to browse our product listing and put together a purchase order. But first, we have a few formalities.</p>

<%= form_for @merchant, url: wholesale_path, method: "post" do |f| %>
  <div>
    <label>
      Please enter your primary email address.
      <div class="info-prompt" toggler-toggle="popup">?</div>
      <%= f.text_field :email, autofocus: true, placeholder: "eg: secret-identity@example.com" %>
    </label>
  </div>
  <%= render 'partials/form_errors', model: @merchant %>
  <div class="perspective">
    <%= f.submit "Continue" %>
  </div>
<% end %>

<div class="info-popup" toggler-target="popup">
  We'll store your account info under this email address. We'll also use it as the main contact address for your account.
  <div class="close" toggler-hide="popup">Close</div>
</div>